### ISSUE TITLE
preserve newlines ?

### ISSUE THREAD

**Issue by rafipiccolo** [wessberg/cjstoesm#10]
hello,
Is it possible ? because it shrinks my code so much its hard to read the output.
i will be forced to create a shitty regexp replacer.
please.

**Comment by wessberg** [comment]
Hey there,

Sorry for the late reply.

`cjstoesm` works on an AST constructed from your source code and then generates a new one from it. Because of that, it is not possible to guarantee the exact same code formatting. Instead, TypeScript emits/prints new text from the constructed AST. This process is somewhat customizable, but with the default settings the result should be pretty-printed. It sounds pretty weird to be that your code becomes basically unreadable. If you provide me a repro or some code example, I'll see if I can make sense of it.

**Comment by rafipiccolo** [comment]
I think I was a bit excessive in my first message but from my point of view all empty lines were deleted, making the code very dense.
My project was already prettified with prettier.
I can understand why your project does that.
Still the output didn't convinced me.
I ended replacing all my projects source using regexps.

Exemple code : 
Newlines are here to separate code into logical parts, to ease reading.
```
var fs = require('fs');

var filename = './test.jpg';
var content = fs.readFileSync(filename);

var a = 1;
var b = 2;
var calcul = a + b;

fs.writeFileSync(filename, content);
```

becomes this : (no empty lines at all)
```
import fs from "fs";
var filename = './test.jpg';
var content = fs.readFileSync(filename);
var a = 1;
var b = 2;
var calcul = a + b;
fs.writeFileSync(filename, content);
```
